name: Compile Build-Packs

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build php-7.3:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Building Compiler
        run: cd php73 && make distribution

  build php-7.4:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Building Compiler
        run: cd php74 && make distribution
  
  build php-8.0:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Building Compiler
        run: cd php80 && make distribution


